# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.1

# Fabric Properties
fabric_loader_version=0.18.5
fabric_api_version=0.144.3+26.1

# Mod Properties
mod_version = 1.2.12-pre1
maven_group = com.gmail.sneakdevs.diamondchestshop
archives_base_name = diamondchestshop

# Dependencies
cloth_config_version=26.1.154
diamond_economy_version=67c2bed7d137ce505c3a4636282110bf5207cdb6